#!/bin/bash

# check source filename

[ -z "$1" ] && echo "No source specified." && exit 1
SOURCEFN="$1"
case "$SOURCEFN" in
    random.c)
        STDSUFF=random
        ;;
    GHZ_QFT.c)
        STDSUFF=GHZ
        ;;
esac


# check target dir

BUILDDIR=build
if [ -n "$2" ]; then
    BUILDDIR="$2"
fi
[ -e "$BUILDDIR" ] && echo "Target \`$BUILDDIR\` exists." && exit 1
mkdir -p "$BUILDDIR"


# build

pushd "$BUILDDIR"
cat >diff.sh <<EOF
#!/bin/bash
diff -s probs.dat ../standards/probs.dat_${STDSUFF}
diff -s stateVector.dat ../standards/stateVector.dat_${STDSUFF}
EOF
chmod +x diff.sh
cmake .. -DUSER_SOURCE="$SOURCEFN" -DCMAKE_C_FLAGS="-std=c99 -g" -DCUDA_NVCC_FLAGS="-g" -DGPU_COMPUTE_CAPABILITY=70 -DGPUACCELERATED=1 -DVERBOSE_CMAKE=ON
#-DCMAKE_CUDA_ARCHITECTURES=70
#-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_RULE_MESSAGES:BOOL=OFF  -Xcompiler
echo --------------- cmake done ---------------
make --no-print-directory

